version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_aws
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_PERSISTENCE=1
      - SERVICES=sns,ses,sqs,lambda,dynamodb
      - DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
      - DEBUG=1
    volumes:
      - "./initialise-resources.sh:/etc/localstack/init/ready.d/initialise-resources.sh"
      - "./localstack-data:/var/lib/localstack" 
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fine-management-app-network
    extra_hosts:
      - "sqs.us-east-1.localhost.localstack.cloud:host-gateway"


networks:
  fine-management-app-network:
    external: true
    name: fine-management-app-network
